-- Organization-wide MI CAR deployments (idempotent H2 migration).
ALTER TABLE permissions DROP CONSTRAINT IF EXISTS chk_permission_domain;
ALTER TABLE permissions ADD CONSTRAINT chk_permission_domain CHECK (permission_domain IN ('Integration-Management','Environment-Management','Project-Management','Observability-Management','User-Management','Workflow-Management','Audit-Management','Deployment-Management'));
MERGE INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) KEY(permission_name) VALUES ('d1f4c2e0-0000-4000-8000-000000000001','deployment_mgt:view','Deployment-Management','deployment','view','View MI deployment operations'),('d1f4c2e0-0000-4000-8000-000000000002','deployment_mgt:manage','Deployment-Management','deployment','manage','Create and execute MI deployment operations');
INSERT INTO role_permission_mapping (role_id, permission_id) SELECT r.role_id,p.permission_id FROM roles_v2 r CROSS JOIN permissions p WHERE r.role_name IN ('Admin','Super Admin') AND p.permission_name IN ('deployment_mgt:view','deployment_mgt:manage') AND NOT EXISTS (SELECT 1 FROM role_permission_mapping x WHERE x.role_id=r.role_id AND x.permission_id=p.permission_id);
CREATE TABLE IF NOT EXISTS mi_deployment_artifacts (artifact_id VARCHAR(36) PRIMARY KEY, file_name VARCHAR(255) NOT NULL, artifact_name VARCHAR(255) NOT NULL, artifact_version VARCHAR(100) NOT NULL, sha256 VARCHAR(64) NOT NULL, file_size BIGINT NOT NULL, content BLOB NOT NULL, expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS mi_deployment_operations (deployment_id VARCHAR(36) PRIMARY KEY, org_id INT NOT NULL, org_handler VARCHAR(255) NOT NULL, artifact_id VARCHAR(36) NOT NULL, status VARCHAR(40) NOT NULL, created_by VARCHAR(255) NOT NULL, parent_deployment_id VARCHAR(36), version INT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS mi_deployment_targets (target_id VARCHAR(36) PRIMARY KEY, deployment_id VARCHAR(36) NOT NULL, project_id VARCHAR(36) NOT NULL, component_id VARCHAR(36) NOT NULL, environment_id VARCHAR(36) NOT NULL, runtime_id VARCHAR(36) NOT NULL, production BOOLEAN NOT NULL, eligible BOOLEAN NOT NULL, conflict BOOLEAN NOT NULL, delete_before_upload BOOLEAN NOT NULL DEFAULT FALSE, phase VARCHAR(40) NOT NULL, attempt INT NOT NULL DEFAULT 0, lease_until TIMESTAMP, http_status INT, reason VARCHAR(1000), message VARCHAR(4000), evidence CLOB, updated_at TIMESTAMP NOT NULL, CONSTRAINT fk_mi_deploy_target_op FOREIGN KEY (deployment_id) REFERENCES mi_deployment_operations(deployment_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS mi_deployment_events (event_id VARCHAR(36) PRIMARY KEY, deployment_id VARCHAR(36) NOT NULL, target_id VARCHAR(36), phase VARCHAR(40) NOT NULL, message VARCHAR(4000) NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_mi_deploy_event_op FOREIGN KEY (deployment_id) REFERENCES mi_deployment_operations(deployment_id) ON DELETE CASCADE);
